### ISSUE TITLE
As a user, I want my search results within a work to be loaded as soon as I enter a search term so that my search experience is consistent across pages. 

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#247] opened 2019-02-12 21:03 UTC
# testing notes
you can test on any item detail page; I usually use [this one](https://test-ppa.cdh.princeton.edu/archive/mdp.39015003633594/).

- when you get to the detail page, you shouldn't see the "no results" screen, just the search box.
- no need to hit <kbd>enter</kbd> inside the search box, and hitting it should have no effect.
- the results should load automatically as you type, with a slight delay similar to the main search (hopefully enough delay time to type most of your search, but also quick enough).
- the result count should update when your results change.
- pagination controls should update when your results change.
- moving to the next/prev page should work normally, and your search should still be there when you get to a new page.
- your search should appear in the URL bar as you type (`?query=something`)
- if you copy-paste the URL after you ran a search into a new tab, it should take you right back to that search, just like it does with the main search
- if you enter a search, then delete everything in the search box, the results should go away completely, just like you had just arrived at the detail page.
- if you turn off javascript using the developer tools, the page should work exactly the way it used to (doesn't automatically load results and you have to press enter, but otherwise the same).

# dev notes
this issue will be a test of our new progressive reactive search implementation; thus it should work both with and without javascript.

**Comment by mnaydan** [comment] 2019-04-09 20:43
All of the features on the testing notes function as expected. The search is fast and responsive! 

Turning off JS led to an issue with the thumbnails (placeholder and thumbnail were stacked, instead of thumbnail replacing placeholder) but Nick fixed this.

There's also a question about jumping behavior that's happening to me in FF on the very first record search. Will leave this open until tomorrow to see if we can reproduce it in person.

**Comment by mnaydan** [comment] 2019-04-10 18:57
I flagged the FF bug as #292 so I am closing this out since everything else is working.

**Closed by mnaydan** 2019-04-10 18:57 UTC
Labels: awaiting testing
